name: allesfitter-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - tqdm
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - dynesty
    - emcee
    - celerite
    - corner
    - rebound
    - wotan
    - transitleastsquares
