name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - ellc
  - dynesty
  - emcee
  - celerite
  - corner
  - rebound
  - wotan
  - transitleastsquares
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
